#!/bin/env bash

set -eu
cd "$(dirname "${BASH_SOURCE[0]}")"

readonly outdir='PsdcSharp/Psdc/bin/publish'

if [[ -e "$outdir" ]]; then
    rm -r "$outdir"
fi
dotnet publish PsdcSharp/Psdc/Psdc.csproj -v n /p:PublishProfile=linux-x64 -o "$outdir"