# yaml-language-server: $schema=https://github.com/5cover/ast-gen/raw/refs/heads/main/schemas/config.json
namespace: Scover.Psdc.StaticAnalysis
root: semantic_node
common_props:
  meta: semantic_metadata