<syntax> ::= "\\begin" "{align*}" (<section> | <top_rule>) (<nl> (<section> | <top_rule>))* <nl>? "\\end" "{align*}"
<section> ::= "\\textbf" "{" <identifier>+ "}"

<top_rule> ::= <rule_name> "&" "\\to " <part>+
<rule> ::= <rule_name> "\\to " <part>+

<part> ::= <item> <modifier>?
         | "{" <rule> "}" <modifier>
         | <rule>

<item> ::= "\\begin" "{cases}" <identifier> (<nl> <identifier>)* <nl>? "\\end" "{cases}"
         | <rule_name>
         | "{" <item>* "}"
         | <terminal>

<terminal> ::= "\\text" "{" <identifier>+ "}"
             | <identifier>

<modifier> ::= "^" "*"
             | "^" "+"
             | "^" "?"
             | "^" "{" "*" <separator> "}"
             | "^" "{" "+" <separator> "}"

<separator> ::= "|" <terminal>

<rule_name> ::= "⟨" <identifier> "⟩"
<nl> ::= "\\\\"
<identifier> ::= ([0-9] | [A-Z] | [a-z])+